
---

- hosts: backend

  tasks:
      - apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'
      - apt: update_cache=yes cache_valid_time=3600
      - apt: name=git state=present
      - apt: name=golang state=present
      - git: repo=git://github.com/juanantoniofm/goapi.git
          dest=/var/www/goapp
          version=release-0.3
      - shell: cd /var/www/goapp; bash install.sh; bash run.sh
